services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - /Users/getway/docker-testapp/data-db:/data/db   # persist MongoDB data

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    depends_on:
      - mongo

  testapp:
    image: testapp:1.0
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - ./testapp-data:/app/data   # mount host folder ./testapp-data to /app/data in container

# Define named volumes
volumes:
  mongo-data:
